Update store.xml
opentorah/alter-rebbe.org pull request #2467
Opened 2020-10-21 10:56 UTC by michaelko58

2020-10-21 14:57 UTC, dubinsky requested changes

2020-10-21 14:57 UTC, dubinsky commented on docs/store/archive/rgia/fund/1309/inventory/1/case/119/rgia119.xml
> +      >Запись в описи на 10 стр.</ref></l>
- ссылка на фотографию страницы из описи - не правильная (не тот фонд, опись, дело, страница);
- фотография ПРАВИЛЬНОЙ страницы описи у нас отсутствует (ты мне ее не предоставил).

2020-10-21 14:57 UTC, dubinsky commented on docs/store/archive/rgia/fund/1343/inventory/39/case/5580/rgia5580.xml
> +    >Запись в описи на 230 стр.</ref></l>
- фотография страницы описи у нас отсутствует (ты мне ее не предоставил).

2020-10-21 14:57 UTC, dubinsky commented on docs/store/archive/rgia/fund/1343/inventory/39/store.xml
> +    </ref>
Сомневаюсь, что ссылкам место в abstractе а не в body.

2020-10-21 14:57 UTC, dubinsky commented on docs/store/archive/rgia/fund/1347/inventory/64-1/case/328/rgia328.xml
> +    >Запись в описи на 32 стр.</ref></l>
- ссылкам место не в abstractе, а в body;
- фотография страницы описи у нас отсутствует (ты мне ее не предоставил).

2020-10-21 14:57 UTC, dubinsky commented on docs/store/archive/rgia/fund/1347/inventory/64-1/case/413/rgia413.xml
> +      >Запись в описи на 39 стр.</ref></l>
- ссылка на фотографию страницы из описи - не правильная (не та опись, страница);
- фотография ПРАВИЛЬНОЙ страницы описи у нас отсутствует (ты мне ее не предоставил).

2020-10-21 14:57 UTC, dubinsky commented on docs/store/archive/rgia/fund/1374/inventory/3/case/2213/rgia2213.xml
> +  смещении в места раввина и разорении его последователями секты шабзус-цвинкус. С приложенивм описания этой секты и
`в места`?  "С приложением..." - это еще название или уже описание?

2020-10-21 14:57 UTC, dubinsky commented on docs/store/archive/rgia/fund/1374/inventory/3/case/2213/rgia2213.xml
> +    <l>Упомянаются: Ф.М. Брискорн,.М.И. Голенищев-Кутузов,З. Карнеев, Неплюев,Розенберг, Торгасов, Тутолкин</l>
- перед Розенбергом пропущен пробел;
- ссылки на имена должны быть в тэгах persName;

2020-10-21 14:57 UTC, dubinsky commented on docs/store/archive/rgia/fund/1374/inventory/3/case/2213/rgia2213.xml
> +      >Запись в описи на 48стр.</ref></l>
- фотография страницы описи у нас отсутствует (ты мне ее не предоставил).

2020-10-22 22:24 UTC, dubinsky commented
@michaelko58 не вижу сдвигов в этом билетике; я добавил подроный список фотографий и отметил, каких нет - https://github.com/opentorah/alter-rebbe.org/issues/2401.

2020-10-23 06:50 UTC, michaelko58 commented on docs/store/archive/rgia/fund/1343/inventory/39/case/5580/rgia5580.xml
> +    >Запись в описи на 230 стр.</ref></l>
https://www.google.com/url?q=https://rgia.su/imageViewer/img?url%3DmZaTmpGekprCzszLzKDMxtGPm5nZnIqNjZqRi6%2BemJrCztmah4vC0Y%2BbmdmQnZWanIvCzcfLxs3Iztmei4uNws7Kx8fZjJqNlp6Tws4%3D&sa=D&source=hangouts&ust=1603521296744000&usg=AFQjCNFK74yFeOXFg_qWsw5Pa5Y0Lw_OgQ

2020-10-23 06:51 UTC, michaelko58 commented on docs/store/archive/rgia/fund/1343/inventory/39/store.xml
> +    </ref>
согласен

2020-10-23 18:01 UTC, dubinsky commented on docs/store/archive/rgia/fund/1343/inventory/39/case/5580/rgia5580.xml
> +    >Запись в описи на 230 стр.</ref></l>
спасибо, но как раз эта фотография у нас уже есть

2020-10-23 18:54 UTC, dubinsky requested changes

2020-10-23 18:54 UTC, dubinsky commented on docs/store/archive/rgia/fund/468/inventory/43/case/529/rgia529.xml
> +    Количество листов 121 </title> <abstract xmlns="http://www.tei-c.org/ns/1.0"> Письмо <persName ref=
@michaelko58
- что такое "внутрення опись", где она "имеется", и чтотако 1743?
- количество листов - это часть НАЗВАНИЯ?

2020-10-23 18:54 UTC, dubinsky commented on docs/store/archive/rgia/fund/1343/inventory/39/case/5580/rgia5580.xml
> +    >Запись в описи на 230 стр.</ref></l>
это - титульный лист описи, а нужна страница из нее, на которой упомянуто дело

2020-10-23 18:54 UTC, dubinsky commented on docs/store/archive/rgia/fund/1347/inventory/64-1/case/328/rgia328.xml
>      </p></abstract>
@michaelko58 зачем весь abstract внутри абзаца?

2020-10-23 18:54 UTC, dubinsky commented on docs/store/archive/rgia/fund/1374/inventory/3/case/2213/rgia2213.xml
> +      З. Карнеев, Неплюев,Розенберг, Торгасов, Тутолкин</l>
@michaelko58 пробел перед Розенбергом по-прежнему пропущен

2020-10-23 18:55 UTC, dubinsky commented on docs/store/archive/rgia/fund/1343/inventory/39/store.xml
> +    </ref>
но двигать их, конечно, придется мне...

2020-10-23 19:31 UTC, dubinsky requested changes

2020-10-23 19:31 UTC, dubinsky commented on docs/store/archive/rgia/fund/1347/inventory/64-1/store.xml
> +  <abstract xmlns="http://www.tei-c.org/ns/1.0"/>
@michaelko58 что, никакого описания?

2020-10-23 19:31 UTC, dubinsky commented on docs/store/archive/rgia/fund/468/inventory/43/case/529/rgia529.xml
> +  1743) ч. I Количество листов 121</title>
@michaelko58 что за внутренняя опись? где она имеется? что такое 1743? и почему все это в названии дела?!

2020-10-23 19:44 UTC, merged